package com.example.ecommerce_java_room.model;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

@Entity
public class Order implements Serializable{
    //Autogenerated key for each Order
    @PrimaryKey(autoGenerate = true)
    private int id;
    private int productId;
    private int userId;
    private double orderPrice;
    private int orderProductQuantity;

    //constructor
    public Order(int id, int productId, int userId, double orderPrice, int orderProductQuantity) {
        this.id = id;
        this.productId = productId;
        this.userId = userId;
        this.orderPrice = orderPrice;
        this.orderProductQuantity = orderProductQuantity;
    }

    //getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public double getOrderPrice() {
        return orderPrice;
    }

    public void setOrderPrice(double orderPrice) {
        this.orderPrice = orderPrice;
    }

    public int getOrderProductQuantity() {
        return orderProductQuantity;
    }

    public void setOrderProductQuantity(int orderProductQuantity) {
        this.orderProductQuantity = orderProductQuantity;
    }
}
