package com.example.ecommerce_java_room.model;


import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

@Entity
public class Product implements Serializable {
    //Autogenerated key for each product
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String imageURL;
    private String title;
    private int quantity;
    private double price;
    private String category;

    //constructor
    public Product(String imageURL, String title, int quantity, double price, String category) {
        this.imageURL = imageURL;
        this.title = title;
        this.quantity = quantity;
        this.price = price;
        this.category = category;
    }

    //getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
}
